[context.production.environment]
  HUGO_VERSION = "0.74.3"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
    for = "/*"
    [headers.values]
        Access-Control-Allow-Origin = "*"
